name: Docker

on:
  workflow_call

jobs:
  build:
      runs-on: ubuntu-latest

       steps:            
          - name: Checkout
            uses: actions/checkout@v3

          - name: Login to Docker Hub
            uses: docker/login-action@v2
            with:
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}
            
          - name: Extract metadata (label et le tag)
            id: meta
            uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
            with:
              images: ${{ secrets.DOCKER_USERNAME }}/cdapi

          - name: Setup docker buildx
            uses: docker/setup-buildx-action@v2

          - name: Build and push
            uses: docker/build-push-action@v4
            with:
              context: .
              file: ./Dockerfile
              push: true
              tags: ${{ steps.meta.output.tags }}
              labels: ${{ steps.meta.output.labels }}